####
  #  Development Checks 
####
GET http://localhost:8000/

{
"email":"ajit.shukla@gmail.com", 
"classId":"24"
}



####
GET http://localhost:8000/
Cookie: hello:yes

{
"email":"ajit.shukla@gmail.com", 
"classId":"24"
}

####
  #  Create And Initialize DataBase
####


####
GET http://localhost:8000/connect


####
  #  Teacher API Code 
####

#Teacher Login
####
POST http://localhost:8000/api/v1/teacher/login

{
"email":"ajit.shukla@abes.ac.in", 
"classId":"24"
}

#Teacher Sets Problem
####
POST http://localhost:8000/api/v1/teacher/setProblem

{
"email":"ajit.shukla@abes.ac.in", 
"classId": "2356", 
"authKey":"176a5a00148b23ee2d", 
"probString":"Description of problem 5", 
"probImage":"base64prblempng", 
"probTitle":"Some Problem"
}

#Get List Of Live Users
####
POST http://localhost:8000/api/v1/teacher/getLiveUsers

{
"email":"ajit.shukla@abes.ac.in", 
"classId":"2356", 
"authKey":"176a5a00148b23ee2d"
}



#Get Program Code OF Student (Specific)
####
POST http://localhost:8000/api/v1/teacher/getProgramCode

{
"email":"ajit.shukla@abes.ac.in",  
"classId":"2356", 
"authKey":"176a5a00148b23ee2d", 
"stEmail":"student@abc.com" 
}





####
  #  Student API Code 
####


#Student Login
POST http://localhost:8000/api/v1/student/login

{
"stEmail":"ajit.shukla@gmail.in", 
"classId":"24"
}


#Student Get Problem Of Specific Class
####
POST http://localhost:8000/api/v1/student/getProblem

{
"stEmail":"ajit.shukla@gmail.in", 
"authKey":"257da6b94f4d477668", 
"classId":"2356"
}

#Student Program Upload
####
POST http://localhost:8000/api/v1/student/sendProgramCode

{
"stEmail":"ajit.shukla@gmail.in", 
"classId":"2356",  
"programCode":"program_code_in_base64_string",
"authKey":"257da6b94f4d477668" 
}




#Cookie Based Api (Auth is passed in Cookie)
####
  #APIs reqd for APIs
####